### ISSUE TITLE
Crawl space during mothers shadow escape

### ISSUE THREAD

**Issue by 8bitendo** [UnderscoreKilburn/repentance-issues#1843] opened 2023-04-05 16:36 UTC
I got a key during mothers shadow escape, and a crawl space appeared after using a red bomb. After leaving the crawl space, key counter has been reset to 0, resulting in a soft lock.

**Comment by ZMBanshee** [comment] 2023-04-05 16:43
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/1722

**Closed as not planned by ZMBanshee** 2023-04-05 16:43 UTC
Labels: duplicate
