### ISSUE TITLE
soul of isaac doesn't handle pickups correctly when item is already touched

### ISSUE THREAD

**Issue by eyhung** [UnderscoreKilburn/repentance-issues#1478] opened 2022-12-25 06:37 UTC
Find an active item on a pedestal while carrying an active item and Soul of Isaac.  Pick up and drop the active item (to get credit for a transformation).  Now use soul of isaac to generate a passive item that generates pickups (like skeleton key).  Pick up skeleton key.  The player does not get the 99 keys.

**Comment by Rchardon** [comment] 2022-12-25 14:23
Duplicate of #308 @ZMBanshee

**Comment by ZMBanshee** [comment] 2022-12-25 14:40
The Soul of Isaac stuff could be merged yeah, there's a few different issues open about it, and even though they describe different problems they're likely all caused by the same bug. I didn't merge them sooner because I'm being lazy today, but I suppose I'll clean them up right now if they bother you lol

**Closed as not planned by ZMBanshee** 2022-12-25 14:40 UTC
Labels: bug, duplicate
