### ISSUE TITLE
Finger moment

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1391] opened 2022-12-11 19:22 UTC
tried searching this everywhere I could on Github but couldn't find it

long story short, the item was able to set enemies on fire etc pre-rep but this was removed for some reason.

dunno if it's intended or an oversight but i wish we got it back that was neat

**Comment by ZMBanshee** [comment] 2022-12-11 19:24
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/1006

**Closed as not planned by ZMBanshee** 2022-12-11 19:24 UTC
Labels: duplicate
