### ISSUE TITLE
range of forgotten's bone club | spirit sword fixed

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1947] opened 2023-09-11 11:27 UTC
https://steamcommunity.com/comment/5/bounce/76561198256204453/3033566163/?feature2=18446744073709551615&tscn=1694405979

this alone would be a 10/10 addition, and considering how much Nuclear Throne inspiration Rep had this would be fitting, way too fitting even

**Comment by Lonrite** [comment] 2023-09-11 16:03
https://steamcommunity.com/sharedfiles/filedetails/?id=3033565322


also this ig

**Comment by ZMBanshee** [comment] 2023-09-11 21:34
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/667

**Closed as not planned by ZMBanshee** 2023-09-11 21:34 UTC
