### ISSUE TITLE
run reroll oversight

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1152] opened 2022-11-09 06:58 UTC
tech 2 stays with you for 1 room even if it disappears after a run reroll like d4

**Comment by ZMBanshee** [comment] 2022-11-09 13:02
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/290

**Closed as not planned by ZMBanshee** 2022-11-09 13:02 UTC
Labels: duplicate

**Comment by Lonrite** [comment] 2022-11-17 06:31
same applies to death tooth's aura
