### ISSUE TITLE
Reworked Tainted Lazarus does not function on Switch

### ISSUE THREAD

**Issue by serrated01** [UnderscoreKilburn/repentance-issues#452] opened 2022-01-22 10:54 UTC
when playing as tainted lazarus, the transparent blue pedestal item in treasure rooms, etc does not appear, nor does the item change when using flip.

**Comment by ZMBanshee** [comment] 2022-01-25 09:07
That's because the Switch port is like three versions behind and needs to be updated by Nicalis and every other third party they have to go through to push the patches out. Not much that we can do about it, so I'm closing this. It's not a bug, he just didn't used to have that feature.

**Closed as completed by ZMBanshee** 2022-01-25 09:07 UTC
