### ISSUE TITLE
With A Pound of Flesh, Tainted Forgotten and Tainted soul can't take pickups surrounded by spikes in shops

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#149] opened 2021-11-18 13:48 UTC

**Comment by ZMBanshee** [comment] 2021-11-18 22:29
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/44

**Closed as completed by ZMBanshee** 2021-11-18 22:29 UTC
Labels: duplicate
