### ISSUE TITLE
Tuff Twins softlock

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#831] opened 2022-08-12 16:52 UTC
this happens somewhat frequently, potentially causing softlocks (without re-entering the game or using the console)
https://clips.twitch.tv/OriginalSourOstrichPupper-fkSf7CWx-bo5lQ49

**Comment by ZMBanshee** [comment] 2022-08-12 20:28
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/39

**Closed as not planned by ZMBanshee** 2022-08-12 20:28 UTC
Labels: duplicate
