### ISSUE TITLE
White champion Tainted Jacob softlock

### ISSUE THREAD

**Issue by gonzalodecamino** [UnderscoreKilburn/repentance-issues#65] opened 2021-11-12 22:26 UTC
White champions are still unkillable if they appear while Dark Esau is present in the room.

**Comment by ZMBanshee** [comment] 2021-11-12 22:27
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/28

**Closed as completed by ZMBanshee** 2021-11-12 22:27 UTC
Labels: duplicate
