### ISSUE TITLE
Found Soul with Card Reading

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1324] opened 2022-12-04 17:49 UTC
he becomes invisible every time you use a portal on floor entrance (similar to how he becomes invisible when jumping into Mother's fight hole)

**Comment by ZMBanshee** [comment] 2022-12-04 17:56
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/811

**Closed as not planned by ZMBanshee** 2022-12-04 17:56 UTC
Labels: duplicate
