### ISSUE TITLE
Eye of the Occult

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#915] opened 2022-09-04 08:23 UTC
don't get me wrong I love this item but it is a bit unfortunate that it removes holy mantle aura

**Comment by ZMBanshee** [comment] 2022-09-04 09:36
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/161

**Closed as not planned by ZMBanshee** 2022-09-04 09:36 UTC
Labels: duplicate
