### ISSUE TITLE
Azazel's Rage 

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1084] opened 2022-11-02 22:00 UTC
Banshee already mentioned Purgatory being worthless in boss challenge rooms / boss rush, however iirc he didn't mention the same thing for Az' Rage so here i am

same stuff basically applies to it sadly

(Edit: nevermind lol, I guess i confused stuff)

**Comment by ZMBanshee** [comment] 2022-11-02 23:46
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/1018

**Closed as not planned by ZMBanshee** 2022-11-02 23:46 UTC
Labels: duplicate

**Comment by Lonrite** [comment] 2022-11-03 14:23
hope that gets fixed 1 day, wish ya'll a smooth sailing of the upcoming patch
