### ISSUE TITLE
Glitter Bombs

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1225] opened 2022-11-16 15:16 UTC
have unseeded drops in dailies which is yikes though idk if it's possible to even solve that problem

**Comment by ZMBanshee** [comment] 2022-11-16 23:13
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/751

**Closed as not planned by ZMBanshee** 2022-11-16 23:13 UTC
Labels: duplicate
