### ISSUE TITLE
Teleport!  bug

### ISSUE THREAD

**Issue by KiraKeepKool** [UnderscoreKilburn/repentance-issues#388] opened 2021-12-23 18:25 UTC
You can be stuck (no mouvement and no tears land) when you use teleport! right after entering a room ! 
I suppose it's frame perfect, because you have to press teleport immediatly after the screen changed, around the shade fade out.

**Comment by ZMBanshee** [comment] 2021-12-24 00:40
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/62

**Closed as completed by ZMBanshee** 2021-12-24 00:40 UTC
Labels: duplicate
