### ISSUE TITLE
car battery inconsistency

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#828] opened 2022-08-11 20:37 UTC
ventricle razor being worthless with car battery was fixed however it still makes shovel useless which is bad

**Comment by ZMBanshee** [comment] 2022-08-11 22:43
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/705

**Closed as not planned by ZMBanshee** 2022-08-11 22:43 UTC
Labels: duplicate
