### ISSUE TITLE
Using Undefined on the frame you enter the next room after exiting a special room cancels the teleport and makes you unable to move

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#1820] opened 2023-03-27 17:08 UTC
https://user-images.githubusercontent.com/33094562/228015004-fe1ce6c4-8cca-474c-aaac-0797bfa59359.mp4

**Comment by ZMBanshee** [comment] 2023-03-28 01:18
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/62

**Closed as not planned by ZMBanshee** 2023-03-28 01:18 UTC
Labels: duplicate
