### ISSUE TITLE
athame

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1530] opened 2023-01-06 18:48 UTC
is ruined by uranus sadly

**Comment by Lonrite** [comment] 2023-01-06 18:54
lots of stuff is ruined by it actually

**Comment by ghost** [comment] 2023-01-06 19:45
Yeah, Uranus or rather freezing in general has some weird interactions. It will prevent you from getting damage from Lusty Blood, make champions not drop stuff until you shatter them and also messes with Deaths List. Would be nice if freezing could be tweaked to count as actually "killing" enemies.

**Comment by ZMBanshee** [comment] 2023-01-07 00:49
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/883

**Closed as not planned by ZMBanshee** 2023-01-07 00:49 UTC
Labels: duplicate
