### ISSUE TITLE
Game crash via Mr. ME!

### ISSUE THREAD

**Issue by OnlyBadNews** [UnderscoreKilburn/repentance-issues#1143] opened 2022-11-08 05:02 UTC
When Mr. ME! is used on the special door in Mines II that leads to Mausoleum, it crashes the game instead of opening the door.

**Comment by ZMBanshee** [comment] 2022-11-08 05:26
I've experienced this before once myself, but for some reason it never happens when trying to intentionally reproduce it. Very mysterious. There's probably something more to it that we don't know about yet.

**Comment by OnlyBadNews** [comment] 2022-11-08 05:35
I haven't tried it too many times, it happened once in my run with cosmetic mods and I played as Tainted Eve. I did it once by accident, then I tried it again in the same run, same issue. I thought maybe it's from Eve or the cloths, so I disabled my mods, restarted the game and tried it with Isaac, and it crashed again. It's a bug that's listed in the Fandom wiki too. Very strange indeed.

**Comment by ZMBanshee** [comment] 2022-11-08 05:37
It's not mod related. But I did notice that if it happens once on the run, it will always happen if you try again. Getting it to start happening in the first place seems to be the hard part. Do you have the seed of that run by any chance?

**Comment by OnlyBadNews** [comment] 2022-11-08 05:53
Damn, I see what u meant now, on the Isaac run the bug didn't occur the second time I tried it (the first time crashed and took me back to the last save point, and because I teleported myself to Mines II, the time was 0:00). Attempting a rerun of my T.Eve run didn't work either. Maybe it's actually randomly decides to bug a run, SCZH VNY7 is the T.Eve seed, just in case, and the Isaac is 0(that's zero, I think)BEM 94LQ. Funny enough, when I tried to enter the Isaac run again for the seed, after I have already managed to open the door, the game crashed before the run could even open. Wow, it's worse than I thought it was.

On a side note, idk if that's how it should be or not, but with the instakill debug turned on, the Bomb Grimaces die and turn into a bunch of red bombs.

**Comment by OnlyBadNews** [comment] 2022-11-08 06:08
Also, I forgot whether I was in Mines II or Ashpit II, but both time that it worked were against the Great Gideon boss. Maybe a mix of stage/boss or boss room?

**Comment by Lonrite** [comment] 2022-11-17 18:14
https://clips.twitch.tv/ExpensiveFastPidgeonTTours-LWmQPKLAteyRXSLs

got it just now on 1.7.9a with mines door. thought it was downpour exclusive but apparently not

I've heard from someone that it crashes both downpour and mines doors so yeah :/

**Comment by Lonrite** [comment] 2022-11-20 20:28
also unrelated but it would be more fitting if the indicator was something like a crying face instead of missile one. something like that would be more fitting for epic fetus and similar entities but it's more of a whatever really

**Comment by ZMBanshee** [comment] 2022-12-04 21:31
There will be a fix related to Mr. Me in the next update that may address this, so I will close this issue whenever that update comes out. Due to the inconsistent nature of this crash, it's difficult to test. I will ask that if anyone here experiences this after the next update to please open a new issue about it.

**Comment by OnlyBadNews** [comment] 2022-12-04 22:33
No problem, let's hope there won't be anymore issues.

**Closed as completed** 2022-12-07 02:51 UTC
Labels: bug, crash, fixed in patch
