### ISSUE TITLE
more epiphora info

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1234] opened 2022-11-17 07:42 UTC
resets when entering boss rooms which is inconsistent with how it doesn't reset upon entering a new floor or taking items

also i still think it should be more similar to dead eye where the tear buff doesn't instantly reset if you mess up

the boss room reset thing is probably a duplicate so ig just lock it if that's the cose

**Comment by ZMBanshee** [comment] 2022-11-17 08:47
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/839

**Closed as not planned by ZMBanshee** 2022-11-17 08:47 UTC
Labels: duplicate
