### ISSUE TITLE
Taking portal from lil portal created before ascent in boss room

### ISSUE THREAD

**Issue by Strinabre** [UnderscoreKilburn/repentance-issues#350] opened 2021-12-12 18:31 UTC
I found a crash easily doable recently, involving portals from lil portal created in boss room, and then taking it from the ascent : 
1- In any boss room, create a portal with lil portal
2- Take the path to The Beast
3- In the same boss room in the ascent, take the previsously created portal
4- Game crashes

Possible solutions : 
1- Make the game not remembering there were a portal in boss rooms when in the ascent.
2- Make it so the said portal works and teleport the player in another room (preferable/make lil portal more versatile in Beast Runs)

**Comment by ZMBanshee** [comment] 2021-12-12 21:59
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/321

**Closed as completed by ZMBanshee** 2021-12-12 21:59 UTC
Labels: duplicate
