### ISSUE TITLE
Finger!

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1006] opened 2022-10-16 05:16 UTC
intentionally or not, finger got nerfed in Repentance and doesn't have status effects anymore like poison or fires getting put on enemies. would be really pog to see that back

**Comment by ZMBanshee** [comment] 2022-10-16 05:22
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/179

**Closed as not planned by ZMBanshee** 2022-10-16 05:22 UTC
Labels: duplicate
