### ISSUE TITLE
Tainted Keeper in Greedier not receiving coins from enemies after first wave

### ISSUE THREAD

**Issue by a-to-zedd** [UnderscoreKilburn/repentance-issues#160] opened 2021-11-18 23:17 UTC
Since the update, when I play Tainted Keeper on Greedier mode, I've played through 9/11 waves (every one except for the bosses), and I only seen ~2 vanishing coins from enemies that spawned after the first wave, total. This has happened on multiple attempts, so it does not appear to be just incredibly bad luck.

**Comment by ZMBanshee** [comment] 2021-11-18 23:20
It'll work as intended if you don't ever leave the starting room to check the item room/shop. Of course, that's not how it's supposed to work, but I'm just letting you know how you can avoid this issue for the time being until a fix can be rolled out.

**Comment by a-to-zedd** [comment] 2021-11-18 23:22
@ZMBanshee Thank you, I appreciate that! I understand if you can't say, or if this is a dumb question for here, but is there a timeline for the next patch containing this fix? (I've also experienced the bug with tainted Eve crashing when using Sump at the wrong time, but I saw the issue for that was labeled fixed as well)

**Comment by ZMBanshee** [comment] 2021-12-03 23:26
The fix for this is released now, figured you'd want to know. Couldn't give you an ETA before.

**Closed as completed by ZMBanshee** 2021-12-03 23:26 UTC
Labels: fixed in patch

**Comment by a-to-zedd** [comment] 2021-12-03 23:50
Great news! Thanks so much for letting me know!
