### ISSUE TITLE
Dr. Fetus bombs not going through obstacles with spectral tears.

### ISSUE THREAD

**Issue by VirusCat24** [UnderscoreKilburn/repentance-issues#1867] opened 2023-04-12 00:47 UTC
Dr. Fetus bombs with spectral tears collide on obstacles when you stand right before it. Sometimes leading to accidental damage. Usually it can go through obstacles as expected.

**Comment by ZMBanshee** [comment] 2023-04-12 02:10
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/790

**Closed as not planned by ZMBanshee** 2023-04-12 02:10 UTC
Labels: duplicate
