### ISSUE TITLE
dice room disappearance

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#2105] opened 2024-06-23 16:04 UTC
if there's too much tears on the screen it just disappears entirely ( similar to how mother's attacks can also disappear if there's too many tears on da screen )

**Comment by ZMBanshee** [comment] 2024-06-24 09:28
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/23

**Closed as not planned by ZMBanshee** 2024-06-24 09:28 UTC
Labels: duplicate
