### ISSUE TITLE
Crash: Hard mode seed MS9V RBB4 - game crashes while flipping in Mines 2 item room

### ISSUE THREAD

**Issue by bobatealee** [UnderscoreKilburn/repentance-issues#121] opened 2021-11-16 20:34 UTC
Was playing multiplayer as Tainted Laz, and used Perthro in the Mines 2 item room. I then took the item on the right, used Flip, and the game crashed.

DMP: [https://cdn.discordapp.com/attachments/803819768578441266/910264861118836776/isaacv1.7.5.0000-20211116-122616-8056-11408.dmp](url)

TXT: [https://cdn.discordapp.com/attachments/803819768578441266/910264911752462387/isaacv1.7.5.0000-20211116-122616-8056-11408.txt](url)

**Comment by ZMBanshee** [comment] 2021-12-01 02:12
I believe the cause of this issue is fixed now, so whenever the next patch comes out let us know if it happens again.

**Closed as completed** 2021-12-03 23:27 UTC
Labels: fixed in patch
