### ISSUE TITLE
Heretic trolling

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1138] opened 2022-11-07 12:09 UTC
old bug but still as annoying as ever
https://clips.twitch.tv/FairDelightfulWormDancingBanana-hhVhXfPWbzaksalK

**Comment by ZMBanshee** [comment] 2022-11-07 16:57
Probably a duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/821 but comment here if this isn't the cause and I'll reopen it

**Closed as not planned by ZMBanshee** 2022-11-07 16:57 UTC
Labels: duplicate
