### ISSUE TITLE
reset state

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#699] opened 2022-05-23 06:24 UTC
i'm 99.9% sure this is known anyway but bringing up for visibility anyways just in case - talking about how paschal candle and bumbo reset after 2nd knife piece

**Comment by ZMBanshee** [comment] 2022-06-02 21:49
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/11

**Closed as completed by ZMBanshee** 2022-06-02 21:49 UTC
Labels: duplicate
