### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1049] opened 2022-10-26 17:43 UTC
really hope against hope this is not duplicate but i wish it didn't ruin exploration points - would gladly take uranus and freezing baby if it didnt

**Comment by ZMBanshee** [comment] 2022-10-27 02:36
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/883

**Closed as not planned by ZMBanshee** 2022-10-27 02:36 UTC
Labels: duplicate
