### ISSUE TITLE
Damocles trolling

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1532] opened 2023-01-07 07:46 UTC
most certainly a duplicate but you shouldn't be able to insta pick up items with Damocles, it is rather irritating

**Comment by ZMBanshee** [comment] 2023-01-07 20:44
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/865

**Closed as not planned by ZMBanshee** 2023-01-07 20:44 UTC
Labels: duplicate
