### ISSUE TITLE
Alt Path gets rid of Keeper's birthright effect.

### ISSUE THREAD

**Issue by blameruno** [UnderscoreKilburn/repentance-issues#312] opened 2021-12-05 19:19 UTC
I did a run with keeper and got birthright but when I went through the mines challenge to get knife piece 2, I permanently lost the extra coin heart, even when entering a new floor.

**Comment by ZMBanshee** [comment] 2022-06-29 01:43
Duplicate of #11

**Closed as not planned by ZMBanshee** 2022-06-29 01:43 UTC
Labels: duplicate
