### ISSUE TITLE
Tainted Lazarus with birthright can't revive with Judas' Shadow, Ankh and Missing poster

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#1851] opened 2023-04-06 21:38 UTC
https://www.twitch.tv/phastos/clip/ColorfulBlatantReindeerPanicVis-HQT1Wo8CRikYY93K

1up, lazarus rags and Dead cat work tho

**Comment by ZMBanshee** [comment] 2023-04-07 19:17
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/937

**Closed as not planned by ZMBanshee** 2023-04-07 19:17 UTC
Labels: duplicate
