### ISSUE TITLE
Cantripped challenge crash

### ISSUE THREAD

**Issue by Eris-GitHub** [UnderscoreKilburn/repentance-issues#1906] opened 2023-06-26 14:29 UTC
Using bag of crafting (as a card) in cantripped challenge will cause the game to crash

**Comment by ZMBanshee** [comment] 2023-06-27 02:01
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/1364

**Closed as not planned by ZMBanshee** 2023-06-27 02:01 UTC
Labels: duplicate
