### ISSUE TITLE
White champions can softlock a run as T. Jacob

### ISSUE THREAD

**Issue by Strinabre** [UnderscoreKilburn/repentance-issues#79] opened 2021-11-13 07:52 UTC
When playing as T. Jacob, white invicible champions are fully unkillable, because Dark Esau seems to be considered an enemy within the room the player is currently in.

This one could be "dodged" by killing Dark Esau before the last update, but now it's complete softlock if :
1. You don't have a bomb
2. You're in the room before Boss Room
3. White Champion in any room in Chest/Dark Room

Bug found by bortmania in Reddit : https://www.reddit.com/r/bindingofisaac/comments/qsolu5/run_is_softlocked_because_champion_that_is/?utm_medium=android_app&utm_source=share

**Comment by ZMBanshee** [comment] 2021-11-13 08:19
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/28

**Closed as completed by ZMBanshee** 2021-11-13 08:19 UTC
Labels: duplicate
