### ISSUE TITLE
Boss room #1065 (Gurdy) doesn't work with duality (it only spawns devil door)

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#753] opened 2022-06-28 20:03 UTC
It might not work with all Gurdy boss rooms, haven't tested it

**Comment by ZMBanshee** [comment] 2022-06-28 22:51
Once the alt path is unlocked none of the boss rooms with only 3 doors will spawn the angel room with Duality, and yes that includes every Gurdy boss room. Something would need to be reworked to address this, either by changing every single boss room that only has 3 doors or changing how Duality functions.

**Comment by ZMBanshee** [comment] 2022-06-29 01:30
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/51

**Closed as not planned by ZMBanshee** 2022-06-29 01:30 UTC
Labels: duplicate

**Comment by Rchardon** [comment] 2022-06-29 08:41
There's a good mod for that where the devil and angel doors are alternating
