### ISSUE TITLE
First blowned Super Tinted Rock doesn't give Small rock anymore

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#1313] opened 2022-12-02 01:09 UTC
It used to be before and i haven't seen it being modified in any patch notes so i don't know if it's intended

**Comment by MashSlyferiux** [comment] 2022-12-07 07:10
Happened to me as well.

**Comment by ZMBanshee** [comment] 2023-02-13 00:15
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/1122

**Closed as not planned by ZMBanshee** 2023-02-13 00:15 UTC
Labels: duplicate
