### ISSUE TITLE
tainted lilith's birthright makes it impossible to go to corpse

### ISSUE THREAD

**Issue by BadsyEdgecat** [UnderscoreKilburn/repentance-issues#76] opened 2021-11-13 05:29 UTC
when the knife is attached to gello, whipping the meat door doesnt open it, locking you out of corpse. i was able to get through because Notched Axe brings the familiar trail back together, but not every player will have that.

**Comment by ZMBanshee** [comment] 2021-11-13 05:30
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/30

**Closed as completed by ZMBanshee** 2021-11-13 05:30 UTC
Labels: duplicate
