### ISSUE TITLE
The Moon? causes a softlock on some level layouts

### ISSUE THREAD

**Issue by Zamiell** [UnderscoreKilburn/repentance-issues#523] opened 2022-02-28 20:01 UTC
Steps to reproduce:

```
seed LPEK 9E9Y
stage 2
g k74
```

**Comment by ZMBanshee** [comment] 2022-03-02 23:26
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/367 but thanks for another seed.

**Closed as completed by ZMBanshee** 2022-03-02 23:26 UTC
Labels: duplicate
