### ISSUE TITLE
New Emperor? Softlock

### ISSUE THREAD

**Issue by MashSlyferiux** [UnderscoreKilburn/repentance-issues#1274] opened 2022-11-25 13:03 UTC
Not sure if you are already working on it but if you use Reverse Emperor card in a Special Shop (the one spawned by the Member Card) you will be sealed in a loop only breakable with another teleport tool, switching room between the two indefinitely

**Comment by ZMBanshee** [comment] 2022-11-30 08:28
Probably a duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/741 but either way it's not happening for me, maybe there's something more to it?

**Closed as not planned by ZMBanshee** 2022-11-30 08:28 UTC
Labels: bug, duplicate
