### ISSUE TITLE
Sulfuric Acid and Terra don't open secret rooms with certain tear modifiers.

### ISSUE THREAD

**Issue by ghost** [UnderscoreKilburn/repentance-issues#1475] opened 2022-12-24 21:18 UTC
When you have one of the items mentioned above and you find certain tear modifiers like Brimstone or Technology, it becomes impossible to open secret rooms by firing at them. Rocks and other obstacles can still be destroyed, but secret room walls no longer break.

**Comment by ZMBanshee** [comment] 2022-12-25 14:42
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/935

**Closed as not planned by ZMBanshee** 2022-12-25 14:42 UTC
Labels: duplicate
