### ISSUE TITLE
keeper with birthright doesn't get it back when going for knife piece 2

### ISSUE THREAD

**Issue by eyhung** [UnderscoreKilburn/repentance-issues#733] opened 2022-06-13 07:48 UTC
When entering the knife piece 2 chase sequence with birthright, keeper goes down to 3 coin hearts since no items work in the area. Upon completion, keeper doesn't get the coin heart back.  Feels like it should be restored.  (Similarly, greed's gullet should be restored in a similar manner, but I didn't check to see how it's handled.)

**Comment by ZMBanshee** [comment] 2022-06-14 09:56
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/11

**Closed as completed by ZMBanshee** 2022-06-14 09:56 UTC
Labels: duplicate
