### ISSUE TITLE
1+1 free pennies dont heal Keeper properly

### ISSUE THREAD

**Issue by BadsyEdgecat** [UnderscoreKilburn/repentance-issues#504] opened 2022-02-20 21:37 UTC
instead of healing two health coins if possible, as expected, it still heals 1 health coin and then gives you a penny in your health count, which is behavior that worked in AB+, but now that keepers can have more than 2 health coins, it should be changed to match

**Comment by ZMBanshee** [comment] 2022-02-21 21:29
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/275

**Closed as completed by ZMBanshee** 2022-02-21 21:29 UTC
Labels: duplicate
