### ISSUE TITLE
Interruptions

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1536] opened 2023-01-07 23:23 UTC
stuff like montezuma's revenge, revelation or maw of the void can interrupt or be interrupted with stuff like brimstone / tech x and all

hard to exactly pinpoint whether or not it's intentional but yeah

**Comment by Rchardon** [comment] 2023-01-08 15:44
Duplicate of #510

**Closed as completed** 2023-01-08 20:30 UTC
