### ISSUE TITLE
Lemegeton wisps' item effects only get properly removed by Genesis after Lemegeton is used again later

### ISSUE THREAD

**Issue by YazawaAkio** [UnderscoreKilburn/repentance-issues#1421] opened 2022-12-15 12:28 UTC
As said in the title, when Genesis is used, Lemegeton wisps' item effects will stay even though all wisps had seemly vanished, and will only properly disappear when the state of Lemegeton wisps is refreshed by a new wisp spawning.

**Comment by ZMBanshee** [comment] 2022-12-15 21:45
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/71

**Closed as not planned by ZMBanshee** 2022-12-15 21:45 UTC
Labels: duplicate
