### ISSUE TITLE
Game crashes when flipping on a Blind Alt Path Item.

### ISSUE THREAD

**Issue by broken-usb** [UnderscoreKilburn/repentance-issues#95] opened 2021-11-15 01:01 UTC
Game crashed when i flipped as T. Laz on a Hidden Alt Path Item.
After taking the hidden item as T. Laz i went and flipped over to his Dead Version to take the second version of the blind item but it resulted in a game crash.

Here are the last 10 lines on the logs;

[INFO] - Spawn Entity with Type(809), Variant(0), Pos(320.00,160.00)
[INFO] - Spawn Entity with Type(33), Variant(0), Pos(560.00,160.00)
[INFO] - Spawn Entity with Type(5), Variant(100), Pos(280.00,400.00)
[INFO] - Spawn Entity with Type(5), Variant(100), Pos(360.00,400.00)
[INFO] - Lua mem usage: 763 KB and 709 bytes
[INFO] - music stopped playing
[INFO] - item taken without exchange
[INFO] - item queue flush
[INFO] - Adding collectible 109 (Money = Power) to player 0 (Lazarus)
[INFO] - Caught exception, writing minidump...

Had no Mods installed.

**Comment by ZMBanshee** [comment] 2021-12-01 02:12
I believe the cause of this is fixed now, so let us know if this happens again after the next patch comes out.

**Closed as completed** 2021-12-03 23:27 UTC
Labels: fixed in patch
