### ISSUE TITLE
rainbow champion lover cheating on u

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#2061] opened 2024-03-17 08:55 UTC
if you befriend rainbow champion lil' bro will keep pulling you in which is pretty annoying, definitely unintended

**Comment by ZMBanshee** [comment] 2024-03-17 21:38
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/1090

**Closed as not planned by ZMBanshee** 2024-03-17 21:38 UTC
Labels: duplicate

**Comment by Lonrite** [comment] 2024-03-17 21:43
oh ye true lol, not like that matters much tbh since I doubt any bugs are getting fixed but w/e
