### ISSUE TITLE
Secret room bug

### ISSUE THREAD

**Issue by Eris-GitHub** [UnderscoreKilburn/repentance-issues#579] opened 2022-03-24 23:44 UTC
If secret room had greed mini boss and there was boss rush neer of it, then wall will get bugged texture and can not be destroyed. (Right door on screenshot).
![20220325013912_1](https://user-images.githubusercontent.com/96450920/160027597-6cfc46b2-04d3-497d-b2a2-fb98c858ab6d.jpg)

**Comment by ZMBanshee** [comment] 2022-03-25 02:57
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/260

**Closed as completed by ZMBanshee** 2022-03-25 02:57 UTC
Labels: duplicate
