### ISSUE TITLE
Keeper's Birthright is taken away during Key Piece 2 sequence, but not regranted

### ISSUE THREAD

**Issue by FloFluoro** [UnderscoreKilburn/repentance-issues#87] opened 2021-11-14 04:37 UTC
If Keeper picks up Birthright before doing the Key Piece 2 sequence, it's revoked after entering the chase area, but never re-granted; Keeper will have the same amount of coin hearts he had prior to picking up Birthright.

**Comment by ncrecc** [comment] 2021-11-14 06:36
May also apply to Maggy's Birthright if she has >12 hearts upon entering the mineshaft?

**Comment by aywee26** [comment] 2022-01-03 22:28
Ran into the same issue.
Regular Keeper, didn't beat Hush yet.
Picked up Old Bandage, then bought Birthright. 4 HP.
Entered mine sequence with 4 HP, while wandering around lost 1 HP.
Regained it back by eating Puberty pills.
Seed: 8G46 NEMW
PC, no mods.

**Comment by ZMBanshee** [comment] 2022-06-29 01:45
Duplicate of #11

**Closed as not planned by ZMBanshee** 2022-06-29 01:45 UTC
Labels: duplicate
