### ISSUE TITLE
Ipecac + Brimstone vs The Beast

### ISSUE THREAD

**Issue by psiwox** [UnderscoreKilburn/repentance-issues#355] opened 2021-12-14 08:02 UTC
The Ipecac and Brimstone synergy will collide with the space between the stalagmites and stalactites resulting in an explosion that causes me to lose my run and become sad

**Comment by ZMBanshee** [comment] 2021-12-15 09:35
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/230

**Closed as completed by ZMBanshee** 2021-12-15 09:35 UTC
Labels: duplicate
