### ISSUE TITLE
Small rock, Blood of the martyr and ceremonial robes damage

### ISSUE THREAD

**Issue by ProjectTZ** [UnderscoreKilburn/repentance-issues#647] opened 2022-04-13 08:10 UTC
Getting additional copies of those items (From diplopia or crooked penny) will not give damage ups

**Comment by ZMBanshee** [comment] 2022-08-28 11:53
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/616

**Closed as not planned by ZMBanshee** 2022-08-28 11:53 UTC
Labels: bug, duplicate
