### ISSUE TITLE
Book of Virtues doesn't work with some pocket actives

### ISSUE THREAD

**Issue by HDMonster1** [UnderscoreKilburn/repentance-issues#1588] opened 2023-01-28 15:21 UTC
Apparently it works with TBethany's Lemegeton, TCain's Bag of Crafting, TJacob's Anima Sola and TEve's Sumptorium... 

...buuuuut doesn't work with TLazarus, TApollyon's Abyss, TMag's Yum Heart and TJudas' Dark Arts. 
Please fix.

**Comment by ZMBanshee** [comment] 2023-01-28 15:56
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/1466

**Closed as not planned by ZMBanshee** 2023-01-28 15:56 UTC
Labels: duplicate
