### ISSUE TITLE
Lodestone on Blue Baby

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#930] opened 2022-09-09 09:39 UTC
because of his fly orbitals, Lodestone makes Blue Baby unbeatable which makes the item untakeable sadly (even if normally it's pretty good), wish this was fixed
https://clips.twitch.tv/PuzzledLitigiousPigeonDBstyle-VVVFueZ5CvJtJxr-

**Comment by ZMBanshee** [comment] 2022-09-09 17:29
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/801

**Closed as not planned by ZMBanshee** 2022-09-09 17:29 UTC
Labels: bug, duplicate
