### ISSUE TITLE
Rework range ups for Forgottens

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#1828] opened 2023-03-29 21:21 UTC
Range ups should extend his melee attack from his body instead of pushing the hitbox of the melee. It's the only character where taking more than 4 range ups is detrimental. It is especially painful on Tainted forgotten when he can't hit a close enemy because it is between the skeleton and the melee attack.

**Comment by ZMBanshee** [comment] 2023-03-30 05:03
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/667

**Closed as not planned by ZMBanshee** 2023-03-30 05:03 UTC
Labels: duplicate
