### ISSUE TITLE
Fire rate of 30 Tears Per Second break some charge based attacks

### ISSUE THREAD

**Issue by Neonomi** [UnderscoreKilburn/repentance-issues#192] opened 2021-11-23 21:09 UTC
The following items breaks with 30 TPS or above:
Cursed Eye
Mom's Knife
C Section
Monstro's Lung

**Comment by ZMBanshee** [comment] 2021-11-24 01:38
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/6
(also cursed eye works fine at 30 tps)

**Closed as completed by ZMBanshee** 2021-11-24 01:38 UTC
Labels: duplicate, fixed in patch
