### ISSUE TITLE
Killing a greed encounter in a secret room locks the wall adjacent to a boss challenge room.

### ISSUE THREAD

**Issue by Kattacka** [UnderscoreKilburn/repentance-issues#1393] opened 2022-12-12 03:07 UTC
Having a greed encounter in a secret room that's adjacent to a boss challenge room will keep the wall adjacent to it boarded up and unable to be bombed. Still plays the wall exploding sound when attempting to bomb it yet boards don't go away.

**Comment by Rchardon** [comment] 2022-12-12 04:20
Duplicate of #260

**Closed as not planned** 2022-12-12 04:26 UTC
Labels: duplicate
