### ISSUE TITLE
Delirious Rag Mega softlocks boss room

### ISSUE THREAD

**Issue by ProjectTZ** [UnderscoreKilburn/repentance-issues#337] opened 2021-12-09 17:07 UTC
![20211210030619_1](https://user-images.githubusercontent.com/36955404/145442850-6108acea-f48b-4631-a71c-947eb8dd2503.jpg)

**Comment by ZMBanshee** [comment] 2022-07-22 07:43
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/299

**Closed as not planned** 2022-07-31 13:20 UTC
Labels: bug
