### ISSUE TITLE
Gemini spawned by Delirious will leave his balls by every door after leaving the room it spawned in

### ISSUE THREAD

**Issue by catinsurance** [UnderscoreKilburn/repentance-issues#992] opened 2022-10-08 08:23 UTC
Charmed Gemini spawned by using Delirious will leave the balls connecting him and his brother by the door of every room you enter. Debug 10 will kill the balls.

Reproduction steps:

1. Get Delirious
2. Use Delirious and get a charmed Gemini from Delirious
3. Leave the room
4. His balls are now eternal

Reproduction video:
https://youtu.be/lbapBknymGk

**Comment by Rchardon** [comment] 2022-10-08 10:54
Duplicate of #668

**Comment by catinsurance** [comment] 2022-10-08 12:47
My bad, I tried searching for it but couldn't find any existing issues.

**Closed as not planned** 2022-10-08 18:59 UTC
Labels: duplicate
