### ISSUE TITLE
Hornfel crash

### ISSUE THREAD

**Issue by UsernameNoIdeas** [UnderscoreKilburn/repentance-issues#2117] opened 2024-08-04 16:05 UTC
The game doesn't like it if you _kill Hornfel's first phase while he rides a minecart through a door_. The game _crashes_, and _resets your floor progress_ to zero.

**Comment by ZMBanshee** [comment] 2024-08-05 05:12
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/585

**Closed as not planned by ZMBanshee** 2024-08-05 05:12 UTC
Labels: duplicate
