### ISSUE TITLE
Tainted keeper cannot complete Greedier mode

### ISSUE THREAD

**Issue by CooperLambaste** [UnderscoreKilburn/repentance-issues#249] opened 2021-12-02 12:54 UTC
If you leave the main room, be it for checking treasuries or having to stop the horde of monsters, upon coming back to said room, enemies stop dropping coins, rendering the mode impossible to complete, since you are unable to purchase enough items.

**Comment by ZMBanshee** [comment] 2021-12-02 13:08
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/160

**Closed as completed by ZMBanshee** 2021-12-02 13:08 UTC
Labels: duplicate, fixed in patch
