### ISSUE TITLE
Bob's Bladder doesn't contribute to the Bob transformation.

### ISSUE THREAD

**Issue by Hesterica** [UnderscoreKilburn/repentance-issues#239] opened 2021-11-30 22:19 UTC
There is only one trinket in the game which contributes to a transformation, kid's drawing, while the most obvious one doesn't do anyhting. The Bob transformation along with Oh Crap are the rarest in the game (except for super bum), and adding trinkets to their pool could help.

**Comment by ZMBanshee** [comment] 2021-12-01 02:09
Duplicate of https://github.com/UnderscoreKilburn/repentance-issues/issues/141

**Closed as completed by ZMBanshee** 2021-12-01 02:09 UTC
Labels: duplicate
