### ISSUE TITLE
Massive Bethany bug 

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1602] opened 2023-01-31 11:44 UTC
glowing hourglass doesn't restore soul heart charges (at least if you go back to Cathedral from Chest for example)

you can use up 60 soul heart charges on the floor, then once you go back to a previous floor with glowing hourglass the charges are gone forever and aren't restored at all

**Comment by Rchardon** [comment] 2023-01-31 13:17
Duplicate of #1405

**Closed as not planned** 2023-01-31 18:02 UTC
Labels: duplicate
