### ISSUE TITLE
Sticky Nickels Replace Nickels and not Pennies (Bug)

### ISSUE THREAD

**Issue by SuportSnek** [UnderscoreKilburn/repentance-issues#1712] opened 2023-02-25 01:58 UTC
Sticky Nickels are strictly inferior to normal nickels, and as such, are one of the only unlocks in the entire game that makes your game harder with 0 reward for the player.

https://twitter.com/edmundmcmillen/status/668844468875890688?s=20

According to this tweet, sticky nickels are supposed to replace normal pennies. However, in game, I'm pretty confident that they replace nickels, instead. This has been a bug for 7 years, and I hope it gets fixed one day.

**Comment by ZMBanshee** [comment] 2023-02-25 11:20
The current behavior is intentional. Thank you for the report, but I will be closing this since I have been able to confirm that it is not a bug.

**Closed as not planned by ZMBanshee** 2023-02-25 11:20 UTC
Labels: works as intended
